web:
  image: classicdriver/debian-wheezy-bitbucket:4.1.0
  ports:
    - "7990:7990"
    - "7999:7999"
  volumes_from:
    - data
  links:
    - db:db

db:
  image: classicdriver/postgres:9.4

data:
  image: classicdriver/debian-wheezy-bitbucket-data
  volumes:
    - ./datavolume:/var/bitbucket_home
