= Bitbucket Server (Docker Image)

== Introduction
ClassicDriver Bitbucket Server Docker container.
Our docker implementation of Bitbucket consist of the following three docker images:

. classicdriver/bitbucket-data
+
A data-volume container
. classicdriver/bitbucket:<BITBUCKET-VERSION>
+
The main bitbucket container
. classicdriver/bitbucket-postgres:9.4
+
The Postgres database

== How to BUILD this image
. Clone the Git repository
+
....
git clone http://<git.host>/docker-bitbucket.git
....
. Browse to the folder of the cloned repository
+
....
cd docker-bitbucket
....
. Build the data-volume docker image with the command
+
....
docker build --rm=true --tag=classicdriver/bitbucket-data data/.
....
. Build the web application docker image with the command
+
....
docker build --rm=true --tag=classicdriver/bitbucket:4.1.0 web/.
....
. Build the Postsgres docker image with the command
+
    
docker build --rm=true --tag=classicdriver/bitbucket-postgres:9.4 postgres/
    
. Test the docker images by running
+
....
docker-compose -f docker-compose-dev.yml up -d
....
For *production* deployments simply run
....
docker-compose up -d
....
. Verify correct setup with a browser by going to
....
http://<docker-machine-ip>:7990
....
. Stop and Remove the containers
....
docker-compose stop && docker-compose rm -v -f
....
